<?php
namespace Ui\Widgets\Table;
use Ui\HTML\Elements\Bases\Span;
use Ui\HTML\Elements\Empties\Br;
use Ui\HTML\Elements\Nested\Div;

/**
 * Class DivCell
 * @package Ui\Widgets\Table
 * @author Didier Moindreau <dmoindreau@gmail.com> on 21/10/2019.
 */
class Cell extends  Div{

    /**
     * @var bool $editable
     */
    private bool $editable = false;

    /**
     * @var mixed|null $value
     */
    private  $value = null;

    /**
     * DivCell constructor.
     * @param bool $editable
     * @param mixed|null $value
     */
    public function __construct($value, bool $editable=false)
    {
        parent::__construct();
        $this->editable = $editable;
        $this->setValue($value);
        if($this->editable)
        {
            $this->setContentEditable();
        }

        $this->setClass('div-cell');
        return $this;
    }

    public function setValue($value)
    {
        if(is_array($value))
        {
            $value = implode(new Span(''), $value);
        }
        if (is_numeric($value)) {
            $value = (string)$value;
        }
        $this->value = $value;
        return $this;
    }

    public function setClass(string $class)
    {
        return parent::setClass('div-cell ' . $class); // TODO: Change the autogenerated stub
    }

    public function __toString(): string
    {
        $this->add($this->value);
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}
